name: WordCloud

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 0'

jobs:
  update-readme:
    name: Update Readme with WordCloud
    runs-on: ubuntu-20.04
    steps:
      - uses: Parply/profile-wordcloud@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          IGNORE_REPOS: "autodoortimed,autodoorparking,autodoor,autowaterextractor,autocrane,autoenginedualpush,autoenginedualswitch,autostartriangle,autostardeltainverter,autoelevator,autocutter,autoenginetimed,autoenginenostop,autoenginestop,autocascadestart,autoenginestart"
          IGNORE_FILE_TYPES: ".pickle,.csv,.png,.jpg,.ico,.env,.tgz,.gz,.zip,.html,.snl,.yml,.RData,.pyptoj,.vue,.gif,__pycache__,.mod,.pdf,.Rdata,.obj,.o,.so,.mp4,.in,.mtx"
          WIDTH: "100%"
          CMAP: "hsv"
